stages:
  - stage: SonarQube
    jobs:
      - job: SonarQube
        steps:
          - script: |
              echo SonarQube checks


  - stage: UnitTesting
    jobs:
      - job: UnitTesting
        steps:
          - script: |
              echo UnitTesting Checks


  - stage: DockerBuild
    jobs:
      - job: DockerBuild
        steps:
          - script: |
              docker build -t ${COMPONENT} .

  - stage: DockerPush
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - job: DockerPush
        steps:
          - script: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 408363025084.dkr.ecr.us-east-1.amazonaws.com
              docker tag ${COMPONENT}:latest 408363025084.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
              docker push 408363025084.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}